travis:
  secure:
    BINSTAR_TOKEN: OVTJRu9BF7mYSvC7xQYsNx+fmCkEJ1PHqaCXdIJ36dOHXRFiaDHwDYc+XYRDmbZ7HA56xBNTXaCxAIqcrbr5RKw4x/oShoK18DI3UEYroXYwXs2YNWZN6gcTesGZaO/u110ooKZ/jCfG+pwB6LJmF0SrdY+Tsy7EvFcit3UtJaEOv9gPTN40OuXnxZ2MlqIRj+kiu0ayStn7DbsFRFsZ5BW0JyDqXP0cjs0pVSaVqmle83rVE9b4cE0nq/dx5y/U5PKyafqGbag0lcKJL3mCSA1zURTtRvT2MvWgaw6pycecyi/HbK1BzZcBd7SPkHI9I2YDYn8N5PuA6N3NpkpcCXcHcP0AywvkCZSE+yyR8r1BFrHF0g3b2OcqoLcnmpm1brh+V0Efyr6846hGnzvE90GeRXEwFK1BFJQrqCAKBYOcahrovklcW0PLYRFcsOwn01BIBFNfCat0iS+aRtgCVuXC2EmFfLTd6WdAVbebOZYNndg8xB024LIS7eRKyD8QjAyAna1o6sIEmd9P815YvSdG0t1KLo08m2hMkwDAJ9loCB+BwID3VvSqnr9/R5Z5iBHgL7ksOBGBlYP8VX3D3+G32UwZP/XW884ZJ7k6Nvi8mydWOSr+0TdtnSFmrfvchn/sz20Rd+tdU9Ng6KH3NFgRuAfET7o3qce36u9fOX8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
